# Generated by Django 5.1.5 on 2025-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(max_length=255)),
                ('business_link', models.URLField(unique=True)),
                ('business_image_url', models.URLField(blank=True, null=True)),
                ('business_category', models.CharField(max_length=100)),
                ('business_summary', models.TextField(blank=True, null=True)),
                ('business_published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2555)),
                ('link', models.URLField(unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='Unknown', max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_title', models.CharField(max_length=255)),
                ('innovation_link', models.URLField(unique=True)),
                ('innovation_image_url', models.URLField(blank=True, null=True)),
                ('innovation_category', models.CharField(default='Uncategorized', max_length=100)),
                ('innovation_summary', models.TextField(blank=True, null=True)),
                ('innovation_created_at', models.DateTimeField(auto_now_add=True)),
                ('business_published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_link', models.URLField(unique=True)),
                ('news_image_url', models.URLField(blank=True, null=True)),
                ('news_category', models.CharField(default='Unknown', max_length=100)),
                ('news_summary', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='SportsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_title', models.CharField(max_length=500)),
                ('sports_link', models.URLField(max_length=1000)),
                ('sports_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('sports_category', models.CharField(default='Unknown', max_length=100)),
                ('sports_summary', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sports Article',
                'verbose_name_plural': 'Sports Articles',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TravelArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_title', models.CharField(max_length=255)),
                ('travel_link', models.URLField(unique=True)),
                ('travel_image_url', models.URLField(blank=True, null=True)),
                ('travel_category', models.CharField(default='Uncategorized', max_length=100)),
                ('travel_summary', models.TextField(blank=True, null=True)),
                ('travel_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
